### ISSUE TITLE
Still some questionable requirements

### ISSUE THREAD

**Issue by jbrucker** [WePays/WePay#157]
This is a continuous of #153.

Do you really need 'wheel'?  For what? `wheel` is used for creating "wheels" and setuptools.

Packages that are needed to run tests, but not needed to run the app normally,
should not be included in requirements.txt.

So, do you need `selenium` to run the app?  Or just for testing?

Packaged needed only for testing can either be added explicitly in your Action scripts on Github 
(or whatever C.I. server you use), or put them in a separate testing-requirements file.

**Comment by Tezigudo** [comment]
I didnt really need `wheel`, the reason that I put it in requirements.txt because I see the messagee **below** while installing requirements on my virtual env
<img width="694" alt="image" src="https://user-images.githubusercontent.com/80502090/204862729-245dc25d-7385-4ab1-9e11-23900d833126.png">


I think that install selenium/(package that need to test) seperately in GitHub Action/Action script are better as you think.
